### ISSUE TITLE
How to implement loading Indicator/Progress bar

### ISSUE THREAD

**Issue by austinmao** [Rezonans/redux-async-connect#38]
How would you go about implementing a loading indicator or progress bar? I am following https://github.com/erikras/react-redux-universal-hot-example

**Comment by sars** [comment]
@austinmao hi
here is example:
https://github.com/sars/appetini-front/blob/appetini/src/containers/App/App.js#L51

does it works for you?

**Comment by austinmao** [comment]
Thanks. I figured it out. Great work on this lib and contributing to react-redux-universal, by the way!

I am doing this with https://github.com/milworm/react-progress-2:

```
  state = {
    isProgressShown: false
  };

  componentWillReceiveProps(next) {
    // hide progress bar if active and async data loaded
    const {isProgressShown} = this.state;
    if (!next.isAsyncDataLoaded && !isProgressShown) {
      Progress.show();
      this.setState({ isProgressShown: true });
    }

    if (next.isAsyncDataLoaded && isProgressShown) {
      Progress.hide();
      this.setState({ isProgressShown: false });
    }
  }
```

Another issue tracker: https://github.com/milworm/react-progress-2/issues/2#issuecomment-185522370

**Comment by sars** [comment]
@austinmao it would make sense to add such examples in both libs (docs)

**Comment by dbismut** [comment]
Hey @sars, I'm new to your lib but it looks fantastic and much simpler to use than what I was doing before.

I'm trying to implement a loading indicator / progressbar in my app main container. However all my route components don't necessarily require asyncConnect, and since `reduxAsyncConnect.loaded` is false by default, the loading indicator always shows for non-async routes. I guess I could circumvent this without too much effort but I was wondering what you thought? Wouldn't it make more sense to have loaded set to true by default?

Thanks!

**Comment by dbismut** [comment]
Hey @austinmao, not sure you should use state in that situation... It will trigger a useless render, I think just an instance variable might just work.

``` javascript
  isProgressShown = false

  componentWillReceiveProps(next) {
    // hide progress bar if active and async data loaded
    if (!next.isAsyncDataLoaded && !this.isProgressShown) {
      Progress.show();
      this.isProgressShown = true;
    }

    if (next.isAsyncDataLoaded && this.isProgressShown) {
      Progress.hide();
      this.isProgressShown = false;
    }
  }
```
